apiVersion: v1
kind: Pod
metadata:
  name: worker-app-for-pod
  labels:
    name: worker-app-for-pod
    app: example-worker-app
  
spec: 
  containers:
  - name: worker-app
    image: dockersamples/examplevotingapp_worker

