apiVersion: v1
kind: Pod
metadata:
  name: postgres-wala-pod
  labels:
    name: postgres-wala-pod
    app: example-voting-app

spec:
  containers:
  - name: postgres
    image: postgres:9.4
    ports:
    - containerPort: 5432