apiVersion: v1
kind: Pod
metadata:
  name: redis-wala-pod
  labels:
    name: redis-wala-pod
    app: example-voting-app

spec:
  containers:
  - name: redis
    image: redis
    ports:
    - containerPort: 6379